services:
  - type: web
    name: my-career-plot
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install && npm run build || true
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
